# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://it-teaching.de/"  # Include trailing slash
# title = "IT-Teaching"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright © 222, Andreas Siebel"
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "de"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[Permalinks]
    post = "/:filename/"

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 202
  identifier = "Blog"
  url = "/"

  [[menu.main]]
  name = "Datenschutz"
  weight = 303
  identifier = "Datenschutz"
  url = "/datenschutz/"

  [[menu.main]]
  name = "Impressum"
  weight = 304
  identifier = "Impressum"
  url = "/impressum/"

  [[menu.main]]
  name = "Projekte"
  weight = 305
  identifier = "About"
  url = "https://projects.opencoding.de/"